apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloud-assistant

configMapGenerator:
- files:
  - assistant.yaml
  name: assistant

resources:
- deployment.yaml
- ingress.yaml
- service.yaml
images:
- name: cloud-assistant
  newName: ghcr.io/jlewi/cloud-assistant
  newTag: commit-a1b29c5
