kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: ingress-nginx
  name: network-loss-ingress-nginx
spec:
  selector:
    namespaces:
      - ingress-nginx
    labelSelectors:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: ingress-nginx
  mode: all
  action: loss
  duration: 60m
  loss:
    loss: '50'
    correlation: '50'
  direction: to