kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: default
  name: account-cluster-viewer-hpcaj

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-cluster-viewer-hpcaj
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["chaos-mesh.org"]
  resources: [ "*" ]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-cluster-viewer-hpcaj
subjects:
- kind: ServiceAccount
  name: account-cluster-viewer-hpcaj
  namespace: default
roleRef:
  kind: ClusterRole
  name: role-cluster-viewer-hpcaj
  apiGroup: rbac.authorization.k8s.io
