apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-edit
  namespace: cloud-assistant
subjects:
- kind: User
  name: arn:aws:iam::381491863923:user/sebastian
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io