# A basic workflow for Go
name: test-go
on: [push]
defaults:
  run:
    shell: bash -ieo pipefail {0}
jobs:
  test:
    name: golang test & build
    # Must run on github hosted runners
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - run: go test ./app/...
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - run: go build ./app/...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          # https://github.com/golangci/golangci-lint/releases
          version: v2.1.6
          # Bump the timeout because we are hitting the default of 1m
          args: --timeout=2m
          # These options work around the errors in this issue
          # https://github.com/golangci/golangci-lint-action/issues/244
          skip-pkg-cache: true
          skip-build-cache: true
