name: bundle-web

on:
  push:
    paths:
      - 'web/**'
      - '.github/workflows/test-web.yaml'
  pull_request:
    paths:
      - 'web/**'
      - '.github/workflows/test-web.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
